#!/usr/bin/env python3
# Minimal script: poll a URL until it returns HTTP 418 and then send a short email notification.
# No external libs required (uses stdlib only).
#
# Configure via environment:
#  - TARGET_URL (default https://fox-towing.com/contact-us)
#  - TO_EMAIL (default foxtowing2021@gmail.com)
#  - SMTP_HOST (default "localhost")
#  - SMTP_PORT (default 25)
#  - SMTP_FROM (default "scanner@localhost")
#  - POLL_INTERVAL (seconds, default 60)
#
# Usage:
#  python3 main.py

import os
import time
import urllib.request
import urllib.error
import smtplib
from email.message import EmailMessage
from datetime import datetime

URL = os.getenv("TARGET_URL", "https://fox-towing.com/contact-us")
TO = os.getenv("TO_EMAIL", "foxtowing2021@gmail.com")
SMTP_HOST = os.getenv("SMTP_HOST", "localhost")
SMTP_PORT = int(os.getenv("SMTP_PORT", "25"))
SMTP_FROM = os.getenv("SMTP_FROM", "scanner@localhost")
INTERVAL = float(os.getenv("POLL_INTERVAL", "60"))
TIMEOUT = 10

def fetch(url):
    req = urllib.request.Request(url, headers={"User-Agent": "ping_notify_min/1.0"})
    try:
        with urllib.request.urlopen(req, timeout=TIMEOUT) as r:
            code = r.getcode()
            body = r.read().decode(errors="replace")
            return code, body
    except urllib.error.HTTPError as e:
        try:
            body = e.read().decode(errors="replace")
        except Exception:
            body = ""
        return e.code, body
    except Exception:
        return None, ""

def send_email(smtp_host, smtp_port, mail_from, mail_to, subject, body):
    msg = EmailMessage()
    msg["From"] = mail_from
    msg["To"] = mail_to
    msg["Subject"] = subject
    msg.set_content(body)
    with smtplib.SMTP(smtp_host, smtp_port, timeout=10) as s:
        s.send_message(msg)

def main():
    print(f"[INFO] polling {URL} -> notify {TO} (interval {INTERVAL}s)")
    while True:
        code, body = fetch(URL)
        now = datetime.utcnow().isoformat() + "Z"
        print(f"[{now}] status={code}")
        if code == 418:
            snippet = (body or "").replace("\n", " ")[:800]
            subject = f"[ALERT] {URL} returned 418"
            body_txt = f"Target: {URL}\nStatus: 418\nTime (UTC): {now}\n\nSnippet:\n{snippet}\n\nThis notification was generated by main.py"
            try:
                send_email(SMTP_HOST, SMTP_PORT, SMTP_FROM, TO, subject, body_txt)
                print("[SENT] notification email sent")
            except Exception as e:
                print("[ERROR] sending email:", e)
            # save full HTML for handoff (optional)
            try:
                with open("last_response.html", "w", encoding="utf-8") as fh:
                    fh.write(body)
                print("[INFO] saved last_response.html")
            except Exception:
                pass
            return 0
        time.sleep(INTERVAL)

if __name__ == "__main__":
    main()
